### ISSUE TITLE
Help on a desing issue

### ISSUE THREAD

**Issue by rahmanshaber** [othermod/DPI-Topper-666#1]
Hi, thanks a lot for sharing your design.
I want to use this design. but i want to use the vsync and hsync also the i2c. So my question is is it possible to use other gpio pin as hsync and vsync?

Also adafruit is telling users to install a Device Tree Blob, your didn't talk about it here. Isn't needed for your design as you didn't used vsync and hsync pins? 
https://learn.adafruit.com/adafruit-dpi-display-kippah-ttl-tft/installation

**Comment by othermod** [comment]
As for the Device Tree Blob, that is no longer required. On newer versions of Raspbian, the GPIO alternate functions can be set using "gpio=..." in config,txt.

I don't use the HSYNC and VSYNC on this board, because the 40-pin displays come preconfigured in DE mode and not need them

![Alternates](http://www.pixelbanane.de/yafu/2790280760/GPIO%20Bank%200.jpg)

Hardware I2C and HSYNC/VSYNC cannot be used at the same time on the 40-pin header because they have to use the same pins. If you design absolutely has to use both I2C and HSYNC/VSYNC, I recommend either using bitbanged I2C or using the hardware I2C pins that are available on the CSI connector (which is GPIOs 28/29 on some Pi boards and 44/45 on others).

**Comment by rahmanshaber** [comment]
Thank you so much for this work, it cleared a lot of my questions. 

One more thing, 

> I don't use the HSYNC and VSYNC on this board, because the 40-pin displays come preconfigured in DE mode and not need them

Can you explain the preconfigured in DE mode, how can i check this in my display of choice. Suppose i am using this from adafruit https://cdn-shop.adafruit.com/product-files/1591/SPEC-CH430WQ01-T_Rev.A.pdf.

**Comment by othermod** [comment]
Look at section 7.2 of that datasheet. 7.2.1 appears to show the typical sync method using VSYNC, HSYNC, and DE to send the front porch, color data, and back porch, 7.2.2 also shows the alternate modes, including DE mode, which only uses the DE pin and clock counting to transmit the data.

Every 40pin LCD I've tested has worked fine in DE mode, as long as the HSYNC and VSYNC pins are connected to GND.

**Comment by rahmanshaber** [comment]
Understood, Thanks a lot for your time.
